### ISSUE TITLE
why need generate deterministic output?

### ISSUE THREAD

**Issue by gzm55** [rsnel/slip0039#1]
Can we use os rng device instead prng to generate identifier or coefficients? The slip0039 seems not require deterministic feature.

**Comment by rsnel** [comment]
Indeed, slip0039 does not require the use of a prng.  But if you do not use a prng, than you cannot prove that the generated wordlist do not contain extra information. Also: the use of a PRNG enables you to reproduce the output of slip0039 on another machine. 

You could use the os RNG to generate the SEED, this is outside the scope of this program.

I'm thinking of moving the SEED input from a commandline switch to standard input.

**Comment by gzm55** [comment]
yeah, every secret input should  avoid the cli arguments. When using os RNG, can we use the signature part (4 bytes in  y=f(254)) in slip0039 to check the content?
